// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpFuMM3ALO0jFrVu1jL5Yb-toxMVZUl4',
    appId: '1:975864479146:web:b5f6a8107a4e1ee975bfd3',
    messagingSenderId: '975864479146',
    projectId: 'bhasabandhuapp-48af3',
    authDomain: 'bhasabandhuapp-48af3.firebaseapp.com',
    storageBucket: 'bhasabandhuapp-48af3.appspot.com',
    measurementId: 'G-SWNCYPXZFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsc4hUgyBYm6j93DPAsaCVIptFN-YOwtU',
    appId: '1:975864479146:android:803de256fc8be1fc75bfd3',
    messagingSenderId: '975864479146',
    projectId: 'bhasabandhuapp-48af3',
    storageBucket: 'bhasabandhuapp-48af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe1eofhHpd4UfKz-7B4CDnQT_Ob9J_h_s',
    appId: '1:975864479146:ios:0d4da31151b6bf6775bfd3',
    messagingSenderId: '975864479146',
    projectId: 'bhasabandhuapp-48af3',
    storageBucket: 'bhasabandhuapp-48af3.appspot.com',
    iosBundleId: 'com.example.witnessDeposition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe1eofhHpd4UfKz-7B4CDnQT_Ob9J_h_s',
    appId: '1:975864479146:ios:0d4da31151b6bf6775bfd3',
    messagingSenderId: '975864479146',
    projectId: 'bhasabandhuapp-48af3',
    storageBucket: 'bhasabandhuapp-48af3.appspot.com',
    iosBundleId: 'com.example.witnessDeposition',
  );
}
